/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ChooseNicknameRouteImport } from './routes/choose-nickname'
import { Route as BiancaRouteImport } from './routes/bianca'
import { Route as AuthGuardRouteImport } from './routes/_auth-guard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as TutorialRouteRouteImport } from './routes/tutorial/route'
import { Route as PlaygroundRouteRouteImport } from './routes/playground/route'
import { Route as AuthGuardIndexRouteImport } from './routes/_auth-guard/index'
import { Route as UsersNicknameRouteImport } from './routes/users/$nickname'
import { Route as MatchesMatchRouteImport } from './routes/matches/$match'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthGuardStoreRouteImport } from './routes/_auth-guard/store'
import { Route as AuthGuardAdmin_guardedRouteImport } from './routes/_auth-guard/_admin_guarded'
import { Route as AuthGuardMeRouteRouteImport } from './routes/_auth-guard/me/route'
import { Route as UsersIdUserIdRouteImport } from './routes/users/id/$userId'
import { Route as AuthGuardAdmin_guardedAdminRouteImport } from './routes/_auth-guard/_admin_guarded/admin'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseNicknameRoute = ChooseNicknameRouteImport.update({
  id: '/choose-nickname',
  path: '/choose-nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const BiancaRoute = BiancaRouteImport.update({
  id: '/bianca',
  path: '/bianca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardRoute = AuthGuardRouteImport.update({
  id: '/_auth-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRouteRoute = TutorialRouteRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRouteRoute = PlaygroundRouteRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardIndexRoute = AuthGuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGuardRoute,
} as any)
const UsersNicknameRoute = UsersNicknameRouteImport.update({
  id: '/users/$nickname',
  path: '/users/$nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchRoute = MatchesMatchRouteImport.update({
  id: '/matches/$match',
  path: '/matches/$match',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGuardStoreRoute = AuthGuardStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthGuardRoute,
} as any)
const AuthGuardAdmin_guardedRoute = AuthGuardAdmin_guardedRouteImport.update({
  id: '/_admin_guarded',
  getParentRoute: () => AuthGuardRoute,
} as any)
const AuthGuardMeRouteRoute = AuthGuardMeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthGuardRoute,
} as any)
const UsersIdUserIdRoute = UsersIdUserIdRouteImport.update({
  id: '/users/id/$userId',
  path: '/users/id/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardAdmin_guardedAdminRoute =
  AuthGuardAdmin_guardedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthGuardAdmin_guardedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/playground': typeof PlaygroundRouteRoute
  '/tutorial': typeof TutorialRouteRoute
  '/': typeof AuthGuardIndexRoute
  '/bianca': typeof BiancaRoute
  '/choose-nickname': typeof ChooseNicknameRoute
  '/error': typeof ErrorRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof AuthGuardMeRouteRoute
  '/store': typeof AuthGuardStoreRoute
  '/register': typeof AuthRegisterRoute
  '/sign-in': typeof AuthSignInRoute
  '/matches/$match': typeof MatchesMatchRoute
  '/users/$nickname': typeof UsersNicknameRoute
  '/admin': typeof AuthGuardAdmin_guardedAdminRoute
  '/users/id/$userId': typeof UsersIdUserIdRoute
}
export interface FileRoutesByTo {
  '/playground': typeof PlaygroundRouteRoute
  '/tutorial': typeof TutorialRouteRoute
  '/': typeof AuthGuardIndexRoute
  '/bianca': typeof BiancaRoute
  '/choose-nickname': typeof ChooseNicknameRoute
  '/error': typeof ErrorRoute
  '/leaderboard': typeof LeaderboardRoute
  '/me': typeof AuthGuardMeRouteRoute
  '/store': typeof AuthGuardStoreRoute
  '/register': typeof AuthRegisterRoute
  '/sign-in': typeof AuthSignInRoute
  '/matches/$match': typeof MatchesMatchRoute
  '/users/$nickname': typeof UsersNicknameRoute
  '/admin': typeof AuthGuardAdmin_guardedAdminRoute
  '/users/id/$userId': typeof UsersIdUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/playground': typeof PlaygroundRouteRoute
  '/tutorial': typeof TutorialRouteRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth-guard': typeof AuthGuardRouteWithChildren
  '/bianca': typeof BiancaRoute
  '/choose-nickname': typeof ChooseNicknameRoute
  '/error': typeof ErrorRoute
  '/leaderboard': typeof LeaderboardRoute
  '/_auth-guard/me': typeof AuthGuardMeRouteRoute
  '/_auth-guard/_admin_guarded': typeof AuthGuardAdmin_guardedRouteWithChildren
  '/_auth-guard/store': typeof AuthGuardStoreRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/matches/$match': typeof MatchesMatchRoute
  '/users/$nickname': typeof UsersNicknameRoute
  '/_auth-guard/': typeof AuthGuardIndexRoute
  '/_auth-guard/_admin_guarded/admin': typeof AuthGuardAdmin_guardedAdminRoute
  '/users/id/$userId': typeof UsersIdUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/playground'
    | '/tutorial'
    | '/'
    | '/bianca'
    | '/choose-nickname'
    | '/error'
    | '/leaderboard'
    | '/me'
    | '/store'
    | '/register'
    | '/sign-in'
    | '/matches/$match'
    | '/users/$nickname'
    | '/admin'
    | '/users/id/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/playground'
    | '/tutorial'
    | '/'
    | '/bianca'
    | '/choose-nickname'
    | '/error'
    | '/leaderboard'
    | '/me'
    | '/store'
    | '/register'
    | '/sign-in'
    | '/matches/$match'
    | '/users/$nickname'
    | '/admin'
    | '/users/id/$userId'
  id:
    | '__root__'
    | '/playground'
    | '/tutorial'
    | '/_auth'
    | '/_auth-guard'
    | '/bianca'
    | '/choose-nickname'
    | '/error'
    | '/leaderboard'
    | '/_auth-guard/me'
    | '/_auth-guard/_admin_guarded'
    | '/_auth-guard/store'
    | '/_auth/register'
    | '/_auth/sign-in'
    | '/matches/$match'
    | '/users/$nickname'
    | '/_auth-guard/'
    | '/_auth-guard/_admin_guarded/admin'
    | '/users/id/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlaygroundRouteRoute: typeof PlaygroundRouteRoute
  TutorialRouteRoute: typeof TutorialRouteRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthGuardRoute: typeof AuthGuardRouteWithChildren
  BiancaRoute: typeof BiancaRoute
  ChooseNicknameRoute: typeof ChooseNicknameRoute
  ErrorRoute: typeof ErrorRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MatchesMatchRoute: typeof MatchesMatchRoute
  UsersNicknameRoute: typeof UsersNicknameRoute
  UsersIdUserIdRoute: typeof UsersIdUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-nickname': {
      id: '/choose-nickname'
      path: '/choose-nickname'
      fullPath: '/choose-nickname'
      preLoaderRoute: typeof ChooseNicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bianca': {
      id: '/bianca'
      path: '/bianca'
      fullPath: '/bianca'
      preLoaderRoute: typeof BiancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guard': {
      id: '/_auth-guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guard/': {
      id: '/_auth-guard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardIndexRouteImport
      parentRoute: typeof AuthGuardRoute
    }
    '/users/$nickname': {
      id: '/users/$nickname'
      path: '/users/$nickname'
      fullPath: '/users/$nickname'
      preLoaderRoute: typeof UsersNicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$match': {
      id: '/matches/$match'
      path: '/matches/$match'
      fullPath: '/matches/$match'
      preLoaderRoute: typeof MatchesMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth-guard/store': {
      id: '/_auth-guard/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthGuardStoreRouteImport
      parentRoute: typeof AuthGuardRoute
    }
    '/_auth-guard/_admin_guarded': {
      id: '/_auth-guard/_admin_guarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardAdmin_guardedRouteImport
      parentRoute: typeof AuthGuardRoute
    }
    '/_auth-guard/me': {
      id: '/_auth-guard/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthGuardMeRouteRouteImport
      parentRoute: typeof AuthGuardRoute
    }
    '/users/id/$userId': {
      id: '/users/id/$userId'
      path: '/users/id/$userId'
      fullPath: '/users/id/$userId'
      preLoaderRoute: typeof UsersIdUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guard/_admin_guarded/admin': {
      id: '/_auth-guard/_admin_guarded/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthGuardAdmin_guardedAdminRouteImport
      parentRoute: typeof AuthGuardAdmin_guardedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthGuardAdmin_guardedRouteChildren {
  AuthGuardAdmin_guardedAdminRoute: typeof AuthGuardAdmin_guardedAdminRoute
}

const AuthGuardAdmin_guardedRouteChildren: AuthGuardAdmin_guardedRouteChildren =
  {
    AuthGuardAdmin_guardedAdminRoute: AuthGuardAdmin_guardedAdminRoute,
  }

const AuthGuardAdmin_guardedRouteWithChildren =
  AuthGuardAdmin_guardedRoute._addFileChildren(
    AuthGuardAdmin_guardedRouteChildren,
  )

interface AuthGuardRouteChildren {
  AuthGuardMeRouteRoute: typeof AuthGuardMeRouteRoute
  AuthGuardAdmin_guardedRoute: typeof AuthGuardAdmin_guardedRouteWithChildren
  AuthGuardStoreRoute: typeof AuthGuardStoreRoute
  AuthGuardIndexRoute: typeof AuthGuardIndexRoute
}

const AuthGuardRouteChildren: AuthGuardRouteChildren = {
  AuthGuardMeRouteRoute: AuthGuardMeRouteRoute,
  AuthGuardAdmin_guardedRoute: AuthGuardAdmin_guardedRouteWithChildren,
  AuthGuardStoreRoute: AuthGuardStoreRoute,
  AuthGuardIndexRoute: AuthGuardIndexRoute,
}

const AuthGuardRouteWithChildren = AuthGuardRoute._addFileChildren(
  AuthGuardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PlaygroundRouteRoute: PlaygroundRouteRoute,
  TutorialRouteRoute: TutorialRouteRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthGuardRoute: AuthGuardRouteWithChildren,
  BiancaRoute: BiancaRoute,
  ChooseNicknameRoute: ChooseNicknameRoute,
  ErrorRoute: ErrorRoute,
  LeaderboardRoute: LeaderboardRoute,
  MatchesMatchRoute: MatchesMatchRoute,
  UsersNicknameRoute: UsersNicknameRoute,
  UsersIdUserIdRoute: UsersIdUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
